name: CI with SonarQube

on:
  push:

jobs:
  sast_scan:
    name: Run SonarQube SAST Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install SonarQube Scanner
        run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip sonar-scanner.zip
          sudo mv sonar-scanner-*/sonar-scanner /usr/local/bin/

      - name: Run SonarQube SAST Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN_PWD }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=my_project_key \
            -Dsonar.host.url=https://your-sonarcloud-instance.com \
            -Dsonar.login=${SONAR_TOKEN}

      - name: Upload SonarQube Report
        uses: actions/upload-artifact@v4
        with:
          name: sonar-report
          path: sonar-report.json

  dast_scan:
    name: Run SonarQube DAST Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SonarQube Scanner
        run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip sonar-scanner.zip
          sudo mv sonar-scanner-*/sonar-scanner /usr/local/bin/

      - name: Run SonarQube DAST Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN_PWD }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=my_project_key \
            -Dsonar.host.url=https://your-sonarcloud-instance.com \
            -Dsonar.login=${SONAR_TOKEN}

      - name: Upload SonarQube DAST Report
        uses: actions/upload-artifact@v4
        with:
          name: sonar-dast-report
          path: sonar-dast-report.json
