name: CI with SAST and DAST

on:
  push:

jobs:
  sast_scan:
    name: Run Bandit SAST Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan
        run: |
          bandit -ll -ii -r . -f json -o bandit-report.json

      - name: Upload Bandit Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bandit-findings
          path: bandit-report.json

  dast_scan:
    name: Run OWASP ZAP DAST Scan
    runs-on: ubuntu-latest
    needs: sast_scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      #  START YOUR APPLICATION HERE
      # Example: Python app
      - name: Start application
        run: |
          python app.py &
          sleep 15

      # 🔍 OWASP ZAP BASELINE SCAN
      - name: Run OWASP ZAP Scan
        run: |
          docker run \ --rm \
            -v "$(pwd):/usr/src" \
           sonarsource/sonar-scanner-cli \
            -Dsonar.login="sqp_b8319ec5f4b1eeec6ad2fa2a19ae4aac6e4547c5" \
             -Dsonar.host.url="http://host.docker.internal:9000" \
               -Dsonar.projectVersion="8.0" \
               -Dsonar.scm.disabled=true

      - name: Upload OWASP ZAP Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-report
          path: zap-report.html
